import Foundation
import SwiftUI
import UIKit

class JournalExportService {

    func generatePDF(
        recordings: [Recording],
        dateRange: String,
        includeAchievements: Bool,
        achievements: [Achievement]
    ) -> Data? {
        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 50
        let contentWidth = pageWidth - margin * 2

        let pdfRenderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        let analyzed = recordings.filter { $0.analysis != nil }
        let totalSessions = recordings.count
        let totalMinutes = Int(recordings.reduce(0.0) { $0 + $1.actualDuration }) / 60
        let avgScore = analyzed.isEmpty ? 0 : analyzed.compactMap { $0.analysis?.speechScore.overall }.reduce(0, +) / analyzed.count
        let scores = analyzed.compactMap { $0.analysis?.speechScore.overall }
        let improvement = scores.count >= 2 ? (scores.last ?? 0) - (scores.first ?? 0) : 0

        let data = pdfRenderer.pdfData { context in
            context.beginPage()
            var y: CGFloat = margin

            // Title
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 28, weight: .bold),
                .foregroundColor: UIColor.label
            ]
            let title = "SpeakUp Progress Journal"
            title.draw(at: CGPoint(x: margin, y: y), withAttributes: titleAttrs)
            y += 40

            // Date range
            let subtitleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 14),
                .foregroundColor: UIColor.secondaryLabel
            ]
            dateRange.draw(at: CGPoint(x: margin, y: y), withAttributes: subtitleAttrs)
            y += 30

            // Separator
            let separatorPath = UIBezierPath()
            separatorPath.move(to: CGPoint(x: margin, y: y))
            separatorPath.addLine(to: CGPoint(x: pageWidth - margin, y: y))
            UIColor.separator.setStroke()
            separatorPath.stroke()
            y += 20

            // Stats section
            let headerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 18, weight: .semibold),
                .foregroundColor: UIColor.label
            ]
            "Summary".draw(at: CGPoint(x: margin, y: y), withAttributes: headerAttrs)
            y += 30

            let bodyAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 14),
                .foregroundColor: UIColor.label
            ]

            let stats = [
                "Total Sessions: \(totalSessions)",
                "Total Practice Time: \(totalMinutes) minutes",
                "Average Score: \(avgScore)/100",
                "Score Change: \(improvement >= 0 ? "+" : "")\(improvement) points",
                "Most Improved: \(mostImprovedMetric(recordings: analyzed))"
            ]

            for stat in stats {
                stat.draw(at: CGPoint(x: margin + 10, y: y), withAttributes: bodyAttrs)
                y += 22
            }

            y += 20

            // Achievements section
            if includeAchievements {
                let unlocked = achievements.filter { $0.isUnlocked }
                if !unlocked.isEmpty {
                    "Achievements Unlocked".draw(at: CGPoint(x: margin, y: y), withAttributes: headerAttrs)
                    y += 30

                    for achievement in unlocked {
                        let text = "\(achievement.icon) \(achievement.title)"
                        text.draw(at: CGPoint(x: margin + 10, y: y), withAttributes: bodyAttrs)
                        y += 22

                        if y > pageHeight - margin - 50 {
                            context.beginPage()
                            y = margin
                        }
                    }
                }
            }

            // Footer
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 10),
                .foregroundColor: UIColor.tertiaryLabel
            ]
            let footer = "Generated by SpeakUp on \(Date().formatted(date: .long, time: .shortened))"
            footer.draw(at: CGPoint(x: margin, y: pageHeight - margin), withAttributes: footerAttrs)
        }

        return data
    }

    private func mostImprovedMetric(recordings: [Recording]) -> String {
        guard recordings.count >= 2 else { return "N/A" }

        let first = recordings.first?.analysis?.speechScore.subscores
        let last = recordings.last?.analysis?.speechScore.subscores

        guard let f = first, let l = last else { return "N/A" }

        let improvements = [
            ("Clarity", l.clarity - f.clarity),
            ("Pace", l.pace - f.pace),
            ("Filler Usage", l.fillerUsage - f.fillerUsage),
            ("Pause Quality", l.pauseQuality - f.pauseQuality)
        ]

        return improvements.max(by: { $0.1 < $1.1 })?.0 ?? "N/A"
    }
}
