import SwiftUI

struct JournalSummaryView: View {
    let totalSessions: Int
    let totalMinutes: Int
    let averageScore: Int
    let improvement: Int
    let unlockedAchievements: Int

    var body: some View {
        VStack(spacing: 16) {
            // Header
            HStack {
                Image(systemName: "waveform.circle.fill")
                    .font(.title2)
                    .foregroundStyle(.teal)

                Text("SpeakUp")
                    .font(.title2.weight(.bold))

                Spacer()
            }

            Divider()

            // Stats grid
            LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: 12) {
                summaryStatCard(icon: "mic.fill", label: "Sessions", value: "\(totalSessions)", color: .teal)
                summaryStatCard(icon: "clock.fill", label: "Minutes", value: "\(totalMinutes)", color: .blue)
                summaryStatCard(icon: "chart.bar.fill", label: "Avg Score", value: "\(averageScore)", color: .green)
                summaryStatCard(icon: "arrow.up.right", label: "Improvement", value: "\(improvement >= 0 ? "+" : "")\(improvement)", color: improvement >= 0 ? .green : .red)
            }

            if unlockedAchievements > 0 {
                HStack {
                    Image(systemName: "trophy.fill")
                        .foregroundStyle(.yellow)
                    Text("\(unlockedAchievements) achievements unlocked")
                        .font(.subheadline.weight(.medium))
                    Spacer()
                }
                .padding(.top, 4)
            }

            // Footer
            Text("Generated by SpeakUp")
                .font(.caption2)
                .foregroundStyle(.tertiary)
        }
    }

    private func summaryStatCard(icon: String, label: String, value: String, color: Color) -> some View {
        VStack(spacing: 6) {
            Image(systemName: icon)
                .font(.title3)
                .foregroundStyle(color)

            Text(value)
                .font(.title2.weight(.bold))

            Text(label)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 12)
        .background {
            RoundedRectangle(cornerRadius: 12)
                .fill(.ultraThinMaterial)
                .overlay {
                    RoundedRectangle(cornerRadius: 12)
                        .fill(color.opacity(0.1))
                }
                .overlay {
                    RoundedRectangle(cornerRadius: 12)
                        .stroke(.white.opacity(0.1), lineWidth: 0.5)
                }
        }
    }
}
