#!/usr/bin/env bash
# Regenerate docs/SURFACE_MAP.md — typed entry points agents should open first.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUT="docs/SURFACE_MAP.md"
TMP="$(mktemp)"

{
  echo "# Surface map"
  echo
  echo "Generated by \`scripts/generate-surface-map.sh\`. Do not hand-edit — re-run the script."
  echo "Use with \`docs/features/README.md\`: open the feature brief, then the type below."
  echo
  echo "Generated: $(date -u +%Y-%m-%dT%H:%MZ)"
  echo

  echo "## App entry"
  echo
  echo "| Kind | Name | Path |"
  echo "|------|------|------|"
  for f in SpeakUp/SpeakUpApp.swift SpeakUp/Views/ContentView.swift; do
    echo "| file | \`$(basename "$f" .swift)\` | \`$f\` |"
  done
  echo

  echo "## ViewModels"
  echo
  echo "| Name | Path |"
  echo "|------|------|"
  find SpeakUp/ViewModels -name '*.swift' -type f 2>/dev/null | sort | while read -r f; do
    name="$(basename "$f" .swift)"
    echo "| \`$name\` | \`$f\` |"
  done
  echo

  echo "## Services"
  echo
  echo "| Name | Path |"
  echo "|------|------|"
  find SpeakUp/Services -name '*.swift' -type f | sort | while read -r f; do
    name="$(basename "$f" .swift)"
    echo "| \`$name\` | \`$f\` |"
  done
  echo

  echo "## Tabs & hubs"
  echo
  echo "| Name | Path |"
  echo "|------|------|"
  for f in \
    SpeakUp/Views/Today/TodayView.swift \
    SpeakUp/Views/Practice/PracticeHubView.swift \
    SpeakUp/Views/History/HistoryView.swift \
    SpeakUp/Views/Curriculum/CurriculumView.swift \
    SpeakUp/Views/Settings/SettingsView.swift
  do
    [[ -f "$f" ]] || continue
    echo "| \`$(basename "$f" .swift)\` | \`$f\` |"
  done
  echo

  echo "## Widget"
  echo
  echo "| Name | Path |"
  echo "|------|------|"
  find SpeakUpWidget -name '*.swift' -type f 2>/dev/null | sort | while read -r f; do
    echo "| \`$(basename "$f" .swift)\` | \`$f\` |"
  done
} >"$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT"
