#!/usr/bin/env bash
# Regenerate docs/SURFACE_MAP.md — typed entry points agents should open first.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
# Same order on macOS and Linux, so CI can diff the committed copy.
export LC_ALL=C

OUT="${1:-docs/SURFACE_MAP.md}"
TMP="$(mktemp)"

# Types declared in a file other than the one it is named for, plus the
# members agents look up by name (Theme tokens, View modifiers, Components).
symbol_index() {
  find SpeakUp SpeakUpWidget -name '*.swift' -type f | sort | while read -r f; do
    local base types members line
    base="$(basename "$f" .swift)"
    types="$(grep -E '^[[:space:]]*(@[A-Za-z]+[[:space:]]+)*((public|private|fileprivate|internal|final|nonisolated|indirect)[[:space:]]+)*(struct|class|enum|protocol|actor|typealias)[[:space:]]+[A-Za-z_][A-Za-z0-9_]*' "$f" \
      | sed -E 's/.*(struct|class|enum|protocol|actor|typealias)[[:space:]]+([A-Za-z_][A-Za-z0-9_]*).*/\2/' \
      | grep -vx "$base" | awk '!seen[$0]++' | paste -sd, - | sed 's/,/, /g' || true)"
    members=""
    case "$f" in
      SpeakUp/Theme/*|SpeakUp/Extensions/*|SpeakUp/Views/Components/*)
        members="$(grep -E '^    ((public|internal|nonisolated|@MainActor)[[:space:]]+)*(static[[:space:]]+(func|let|var)|func)[[:space:]]+[a-z][A-Za-z0-9_]*' "$f" \
          | grep -vE 'private' \
          | sed -E 's/^.*(func|let|var)[[:space:]]+([a-z][A-Za-z0-9_]*).*/\2/' \
          | awk '!seen[$0]++' | paste -sd, - | sed 's/,/, /g' || true)"
        ;;
    esac
    [[ -z "$types$members" ]] && continue
    line="$types"
    [[ -n "$members" ]] && line="${line:+$line · }$members"
    echo "| \`$f\` | $line |"
  done
}

{
  echo "# Surface map"
  echo
  echo "Generated by \`scripts/generate-surface-map.sh\`. Do not hand-edit — re-run the script."
  echo "Use with \`docs/features/README.md\`: open the feature brief, then the type below."
  echo "Looking for a type, token or modifier by name: \`grep -n 'Name' docs/SURFACE_MAP.md\`."
  echo

  echo "## App entry"
  echo
  echo "| Kind | Name | Path |"
  echo "|------|------|------|"
  for f in SpeakUp/SpeakUpApp.swift SpeakUp/Views/ContentView.swift; do
    echo "| file | \`$(basename "$f" .swift)\` | \`$f\` |"
  done
  echo

  echo "## ViewModels"
  echo
  echo "| Name | Path |"
  echo "|------|------|"
  find SpeakUp/ViewModels -name '*.swift' -type f 2>/dev/null | sort | while read -r f; do
    name="$(basename "$f" .swift)"
    echo "| \`$name\` | \`$f\` |"
  done
  echo

  echo "## Services"
  echo
  echo "| Name | Path |"
  echo "|------|------|"
  find SpeakUp/Services -name '*.swift' -type f | sort | while read -r f; do
    name="$(basename "$f" .swift)"
    echo "| \`$name\` | \`$f\` |"
  done
  echo

  echo "## Design system"
  echo
  echo "| Name | Path |"
  echo "|------|------|"
  find SpeakUp/Theme SpeakUp/Views/Components -name '*.swift' -type f | sort | while read -r f; do
    echo "| \`$(basename "$f" .swift)\` | \`$f\` |"
  done
  echo

  echo "## Tabs & hubs"
  echo
  echo "| Name | Path |"
  echo "|------|------|"
  for f in \
    SpeakUp/Views/Today/TodayView.swift \
    SpeakUp/Views/Practice/PracticeHubView.swift \
    SpeakUp/Views/History/HistoryView.swift \
    SpeakUp/Views/Curriculum/CurriculumView.swift \
    SpeakUp/Views/Settings/SettingsView.swift
  do
    [[ -f "$f" ]] || continue
    echo "| \`$(basename "$f" .swift)\` | \`$f\` |"
  done
  echo

  echo "## Widget"
  echo
  echo "| Name | Path |"
  echo "|------|------|"
  find SpeakUpWidget -name '*.swift' -type f 2>/dev/null | sort | while read -r f; do
    echo "| \`$(basename "$f" .swift)\` | \`$f\` |"
  done
  echo

  echo "## Symbol index"
  echo
  echo "Types living in a differently named file, plus Theme / Extensions / Components members."
  echo
  echo "| File | Symbols |"
  echo "|------|---------|"
  symbol_index
} >"$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT"
